const insights = [
  { id: "evidence", label: "MATERIALS INFORMATICS", title: "Where materials-AI data actually comes from", lede: "A model-ready table is not the same as independent experimental evidence.", body: ["In materials R&D, a useful dataset is rarely born in a single place. It may begin as an instrument export, a formulation notebook, a supplier document, or a reported value in a paper. The central question is not only whether a value can be collected, but how it was measured, transformed, and checked.", "That provenance affects whether a model can learn something useful. A glass transition temperature, for example, is only comparable when its measurement method, sample history, and interpretation are visible enough to evaluate. Automation can make collection faster; it should also make the evidence trail clearer."], takeaway: "Start by mapping one decision back to its source evidence before deciding what to model." },
  { id: "features", label: "SCIENTIFIC AI", title: "Physics-aware features are not physics-aware machine learning", lede: "A useful representation is valuable, but it does not turn a prediction into a physical explanation.", body: ["Domain knowledge can make a machine-learning dataset much more useful. Chemical descriptors, processing conditions, morphology indicators, and experimentally meaningful ratios can all give a model a better starting point than a list of arbitrary columns.", "But a feature designed with physical intuition is not itself proof of a mechanism. A model may identify a robust predictive relationship while the causal explanation still needs targeted experiments. The practical goal is to use the model to generate better questions, then test them with the right evidence."], takeaway: "Use domain knowledge to improve the question and the representation—then keep experimental validation in the loop." },
  { id: "human-loop", label: "AI PRACTICE", title: "What should remain human in an AI-assisted workflow?", lede: "Automation can extend judgment; it should not hide responsibility.", body: ["The best candidate for automation is routine, repeatable work: importing files, applying an agreed calculation, producing a review image, or assembling a traceable table. These are the parts of a workflow where consistency and speed release time for more valuable scientific thinking.", "The expert still decides whether the signal is meaningful, whether a boundary condition invalidates the result, and whether the next experiment is worth running. Good workflow design makes those decisions explicit rather than burying them inside a black box."], takeaway: "Automate the routine, and design visible review points for the decisions that require expertise." },
];

export default function InsightsPage() {
  return <main className="inner-page"><header className="site-header"><a className="wordmark" href="/" aria-label="Song Zhang home">SONG <span>ZHANG</span></a><nav aria-label="Primary navigation"><a href="/">Home</a><a href="/#research">Research</a><a href="/insights">Blog</a><a href="/#advisory">Advisory</a></nav><a className="header-cta" href="/readiness">Readiness check <span>↗</span></a></header><section className="insights-hero section-shell"><p className="eyebrow">BLOG</p><h1>Thoughts, practices, and reading notes.</h1><p>Short writing on practical materials R&amp;D, data workflows, and responsible AI use.</p></section><section className="insight-list section-shell" aria-label="Blog">{insights.map((insight, index) => <article className="insight-article" id={insight.id} key={insight.id}><p className="note-number">0{index + 1} / {insight.label}</p><h2>{insight.title}</h2><p className="insight-lede">{insight.lede}</p>{insight.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className="insight-takeaway"><span>TAKEAWAY</span>{insight.takeaway}</p></article>)}</section><section className="case-close section-shell"><p className="eyebrow">YOUR NEXT STEP</p><h2>Choose one workflow worth clarifying.</h2><p>Take the short readiness check, or book a fit call if you already have a concrete question.</p><a className="button button-dark" href="/readiness">Take the readiness check <span>→</span></a></section><footer><span>© {new Date().getFullYear()} Song Zhang</span><span>FORMULATION DEVELOPMENT × MATERIALS AI</span><a href="#top">Back to top ↑</a></footer></main>;
}
